"""Harness adapters generated by setup.py (Antigravity 2.0 + shared helpers)."""

import importlib.util
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def load_setup():
    spec = importlib.util.spec_from_file_location("fk_setup", ROOT / "setup.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def setup_mod():
    return load_setup()


@pytest.fixture
def sample_skills():
    return [
        {
            "name": "create-project",
            "description": "Create a new Google Flow video project. Ask the user for:",
            "path": "skills/fk-create-project.md",
        },
        {
            "name": "doctor",
            "description": "Diagnose any FlowKit error and prescribe a fix.",
            "path": "skills/fk-doctor.md",
        },
    ]


def test_yaml_scalar_is_single_line_quoted(setup_mod):
    out = setup_mod._yaml_scalar('Say "hello"\nthen deploy')
    assert out.startswith('"') and out.endswith('"')
    assert "\n" not in out
    assert '\\"' in out


def test_antigravity_description_strips_ask_clause_keeps_ellipsis(setup_mod):
    desc = setup_mod._antigravity_description(
        {
            "name": "create-project",
            "description": "Create a new Google Flow video project. Ask the user for:",
        }
    )
    assert desc == (
        "Create a new Google Flow video project. "
        "Use when the user says /fk-create-project."
    )
    assert "Ask the user for" not in desc

    uuids = setup_mod._antigravity_description(
        {
            "name": "fix-uuids",
            "description": (
                "Find and fix any non-UUID media_ids (CAMS... format) "
                "across all scenes and entities"
            ),
        }
    )
    assert "CAMS... format" in uuids
    assert "/fk-fix-uuids" in uuids


def test_discover_skills_finds_fk_files(setup_mod):
    skills = setup_mod.discover_skills()
    names = {s["name"] for s in skills}
    assert "create-project" in names
    assert "gen-refs" in names
    assert all(s["description"] for s in skills)


def test_generate_antigravity_writes_skills_workflows_rules(
    setup_mod, sample_skills, tmp_path, monkeypatch
):
    agents = tmp_path / ".agents"
    legacy = tmp_path / ".agent"
    agents_md = tmp_path / "AGENTS.md"
    monkeypatch.setattr(setup_mod, "AGENTS_SKILLS_DIR", agents / "skills")
    monkeypatch.setattr(setup_mod, "AGENTS_WORKFLOWS_DIR", agents / "workflows")
    monkeypatch.setattr(setup_mod, "AGENTS_RULES_DIR", agents / "rules")
    monkeypatch.setattr(setup_mod, "LEGACY_AGENT_WORKFLOWS_DIR", legacy / "workflows")
    monkeypatch.setattr(setup_mod, "LEGACY_AGENT_RULES_DIR", legacy / "rules")
    monkeypatch.setattr(setup_mod, "AGENTS_MD", agents_md)

    count = setup_mod.generate_antigravity(sample_skills)
    assert count == 2

    skill_md = (agents / "skills" / "fk-create-project" / "SKILL.md").read_text(
        encoding="utf-8"
    )
    assert skill_md.startswith("---\n")
    assert "name: fk-create-project\n" in skill_md
    assert "description:" in skill_md
    assert "/fk-create-project" in skill_md
    assert "skills/fk-create-project.md" in skill_md
    assert "description: >" not in skill_md

    wf = (agents / "workflows" / "fk-doctor.md").read_text(encoding="utf-8")
    assert wf.startswith("---\n")
    assert "description:" in wf
    assert "skills/fk-doctor.md" in wf

    legacy_wf = legacy / "workflows" / "fk-doctor.md"
    assert legacy_wf.exists()

    rule = (agents / "rules" / "flowkit.md").read_text(encoding="utf-8")
    assert "AUTO-GENERATED by setup.py" in rule
    assert "Media ID is always UUID" in rule
    assert "/fk-create-project" in rule
    assert len(rule) < 12_000

    assert (legacy / "rules" / "flowkit.md").exists()
    assert agents_md.exists()
    assert "AUTO-GENERATED by setup.py" in agents_md.read_text(encoding="utf-8")


def test_clean_removes_generated_antigravity_files(
    setup_mod, sample_skills, tmp_path, monkeypatch
):
    agents = tmp_path / ".agents"
    legacy = tmp_path / ".agent"
    monkeypatch.setattr(setup_mod, "AGENTS_SKILLS_DIR", agents / "skills")
    monkeypatch.setattr(setup_mod, "AGENTS_WORKFLOWS_DIR", agents / "workflows")
    monkeypatch.setattr(setup_mod, "AGENTS_RULES_DIR", agents / "rules")
    monkeypatch.setattr(setup_mod, "LEGACY_AGENT_WORKFLOWS_DIR", legacy / "workflows")
    monkeypatch.setattr(setup_mod, "LEGACY_AGENT_RULES_DIR", legacy / "rules")
    monkeypatch.setattr(setup_mod, "AGENTS_MD", tmp_path / "AGENTS.md")
    monkeypatch.setattr(setup_mod, "GEMINI_MD", tmp_path / "GEMINI.md")
    monkeypatch.setattr(setup_mod, "CLAUDE_COMMANDS_DIR", tmp_path / ".claude" / "commands")
    monkeypatch.setattr(
        setup_mod, "GEMINI_COMMANDS_DIR", tmp_path / ".gemini" / "commands" / "fk"
    )
    monkeypatch.setattr(setup_mod, "STATE_FILE", tmp_path / ".fk-setup.json")

    setup_mod.generate_antigravity(sample_skills)
    assert (agents / "skills" / "fk-doctor").is_dir()

    setup_mod.do_clean()
    assert not (agents / "skills" / "fk-doctor").exists()
    assert not (agents / "workflows" / "fk-doctor.md").exists()
    assert not (agents / "rules" / "flowkit.md").exists()
    assert not (legacy / "workflows" / "fk-doctor.md").exists()
    assert not (tmp_path / "AGENTS.md").exists()
